# Generated by Django 4.2 on 2023-05-03 11:31

import bfsapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='account_no',
            field=models.PositiveIntegerField(default=bfsapp.models.generate_account_no, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfsapp.accountholder')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
