# Generated by Django 4.2 on 2023-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfsapp', '0002_alter_accountholder_account_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
