# Generated by Django 4.2 on 2023-05-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfsapp', '0005_accountholder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='user',
        ),
    ]
